export enum EnvKeys {
  PORT = "PORT",
  DATABASE_URL = "DATABASE_URL",
  JWT_ACCESS_SECRET = "JWT_ACCESS_SECRET",
  JWT_ACCESS_TTL = "JWT_ACCESS_TTL",
  JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET",
  JWT_REFRESH_TTL = "JWT_REFRESH_TTL",
  BCRYPT_COST = "BCRYPT_COST",
  NODE_ENV = "NODE_ENV",
}
